name: Topic
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Check out code
        uses: actions/checkout@v5

      - name: go fmt
        run: test -z $(gofmt -l .)

      - name: run go vet
        run: go vet

      - name: golint
        run: go install golang.org/x/lint/golint@latest && golint -set_exit_status ./...

      - name: run test
        run: go test
