name: Topic
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Check out code
      uses: actions/checkout@v3

    - name: run go vet
      run: go vet

    - name: run test
      run: go test
